from django.urls import path
from . import views

urlpatterns =[
    path('',views.home,name='home'),
    path('saudi/',views.saudi,name='saudi'),
    path('kuwait/',views.kuwait,name='kuwait'),
    path('UAE/',views.UAE,name='UAE'),
    path('qatar/',views.qatar,name='qatar'),
    path('Jordan/',views.Jordan,name='Jordan'),
    path('bahrain/',views.bahrain,name='bahrain'),
    path('Oman/',views.Oman,name='Oman'),
    path('Palestine/',views.Palestine,name='Palestine'),
    path('Iraq/',views.Iraq,name='Iraq'),
    path('Lebanon/',views.Lebanon,name='Lebanon'),
    path('algeria/',views.algeria,name='algeria'),
    path('morocco/',views.morocco,name='morocco'),
    path('gold_prices_today/',views.goldpricestoday,name='goldpricestoday'),
    path('gold_prices_today/article/',views.article,name='article'),
    path('gold_prices_today/article_saudi/',views.article_saudi,name='article_saudi'),
    path('gold_prices_today/article_kuwait/',views.article_kuwait,name='article_kuwait'),
    path('gold_prices_today/article_uae/',views.article_uae,name='article_uae'),
    path('gold_prices_today/article_qatar/',views.article_qatar,name='article_qatar'),
    path('gold_prices_today/article_jordan/',views.article_jordan,name='article_jordan'),
    path('gold_prices_today/article_bahrain/',views.article_bahrain,name='article_bahrain'),
    path('gold_prices_today/article_oman/',views.article_oman,name='article_oman'),
    path('gold_prices_today/article_palestine/',views.article_palestine,name='article_palestine'),
    path('gold_prices_today/article_iraq/',views.article_iraq,name='article_iraq'),
    path('gold_prices_today/article_lebanaon/',views.article_lebanaon,name='article_lebanaon'),
    path('gold_prices_today/article_algeria/',views.article_algeria,name='article_algeria'),
    path('gold_prices_today/article_marocco/',views.article_marocco,name='article_marocco'),
    path('about/',views.about,name='about'),
    path('privacy/',views.privacy,name='privacy'),
    path('gold_price_forecast/',views.GoldPriceForecast,name='gold-price-forecast'),
    path('bitcoin_price_forecast/',views.BitcoinPriceForecast,name='bitcoin-price-forecast'),
    path('dollar_price_today/',views.DollarPricetoday,name='dollar-price-today'),
    path('news/',views.news,name='news'),
    path('detail/<int:post_id>/',views.Post_detail,name='detail'),
    path('contact_us/',views.contact_us,name='contact_us'),
]